image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.2.2"

stages:
  - notify
  - build
  - test
  - pre-deploy
  - pre-publish
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PANDA_SDK_VERSION: "1.5.0-dev.31052"

include:
    - gitlab/setup.yml
    - gitlab/npm.yml
    - gitlab/notify.yml
    - arkgen/.gitlab-ci.yml
    - ohosgen/.gitlab-ci.yml
    - arktscgen/.gitlab-ci.yml
    - dtsgen/.gitlab-ci.yml
    - etsgen/.gitlab-ci.yml
