image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.1"
variables:
  GIT_SUBMODULE_STRATEGY: recursive

idlize build:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - npm config set registry https://repo.huaweicloud.com/repository/npm/
    - npm config set @ohos:registry https://repo.harmonyos.com/npm/
    - npm i --no-audit --no-fund
  script:
    - npm run compile

pg check peers run:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - npm config set registry https://repo.huaweicloud.com/repository/npm/
    - npm config set @ohos:registry https://repo.harmonyos.com/npm/
    - npm i --no-audit --no-fund
  script:
    - npm run check:peers:run

