image: "${KOALA_CI_IMAGE}"

stages:
  - notify
  - pre-build
  - build
  - test
  - pre-deploy
  - pre-publish
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PANDA_SDK_VERSION: "1.5.0-dev.39323"

default:
  cache:
  - key: $CI_PIPELINE_ID
    policy: pull
    paths:
    - .npm/

include:
    - gitlab/setup.yml
    - gitlab/npm.yml
    - gitlab/notify.yml
    - arkgen/.gitlab-ci.yml
    - ohosgen/.gitlab-ci.yml
    - arktscgen/.gitlab-ci.yml
    - dtsgen/.gitlab-ci.yml
    - etsgen/.gitlab-ci.yml
    - idlinter/.gitlab-ci.yml
    - interfaces/.gitlab-ci.yml
