image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.2"

stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.setup:
    script:
        - npm config set @ohos:registry https://repo.harmonyos.com/npm/
        - npm config set @koalaui:registry https://nexus.bz-openlab.ru:10443/repository/koala-npm/
        - npm config set @panda:registry https://nexus.bz-openlab.ru:10443/repository/koala-npm/
        - npm config set //nexus.bz-openlab.ru:10443/repository/koala-npm/:_auth $NEXUS_NPM_PASS
        - npm i --no-audit --no-fund
        - npm i --prefix external --no-audit --no-fund

idlize sanity:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - npm run sanity

pg java:run:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 npm run run:java

compile arkts subset:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - PANDA_SDK_VERSION=1.5.0-dev.7123 npm run panda:sdk:install
  script:
    - npm run compile:all:arkts

arkts subset tsc:
   stage: test
   tags:
     - idlize-ci
     - koala-ci
   before_script:
     - !reference [.setup, script]
   script:
     - npm run check:arkts:subset:tsc

arkts subset sig integration:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - PANDA_SDK_VERSION=1.5.0-dev.7123 npm run panda:sdk:install
  script:
    - npm run sig:arkts:subset:all

build arkoala-ts:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run arkoala:ts

#build arkoala-ts-native-arm64:
#  stage: test
#  allow_failure: true
#  tags:
#    - idlize-ci
#    - koala-ci
#  before_script:
#    - !reference [.setup, script]
#  script:
#    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run arkoala:ts:native:arm64
#
#build arkoala-ts-native-arm32:
#  stage: test
#  allow_failure: true
#  tags:
#    - idlize-ci
#    - koala-ci
#  before_script:
#    - !reference [.setup, script]
#  script:
#    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run arkoala:ts:native:arm32

# todo: enable when meson is configured on CI
#build arkoala.har:
#  stage: test
#  tags:
#    - idlize-ci
#    - koala-ci
#  before_script:
#    - !reference [.setup, script]
#  script:
#    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run arkoala:har-arm32
#    - cp $CI_PROJECT_DIR/external/arkoala/har/app/arkoala/build/default/outputs/default/arkoala.har $CI_PROJECT_DIR/
#  artifacts:
#      expire_in: 1 week
#      paths:
#          - arkoala.har

publish idlize:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"
        when: never
      - if: $CI_COMMIT_BRANCH == "master"
        when: on_success
    before_script:
      - !reference [.setup, script]
    script:
        - cd $CI_PROJECT_DIR
        - sed -i "s/+devel/-dev.$CI_PIPELINE_IID/" package.json
        - KOALA_BZ=1 npm run upload

