image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.1"

idlize build:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - npm ci --no-audit --no-fund
  script:
    - npm run compile

pg check peers run:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - npm ci --no-audit --no-fund
  script:
    - npm run check:peers:run

