image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.2.2"

stages:
  - build
  - test
  - pre-deploy
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

include:
    - gitlab/setup.yml
    - gitlab/npm.yml
    - libarkts-gen/.gitlab-ci.yml

check generated XML demo:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    before_script:
      - !reference [.setup, script]
      - cd $CI_PROJECT_DIR/ohosgen
      - PANDA_SDK_VERSION=next npm run panda:sdk:install
      - npm run compile --prefix ../external/interop
      - npm run compile --prefix ../external/incremental/common
      - npm run compile --prefix ../external/incremental/compat
      - npm run compile --prefix ../external/incremental/runtime
      - npm run build:interop:inc --prefix ../external/interop
      - npm run build:incremental:inc --prefix ../external/incremental/runtime
    script:
      - cd demos/xml
      - npm run check:ts
      - npm run check:arkts

check ohos demos:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - cd $CI_PROJECT_DIR/ohosgen
    - PANDA_SDK_VERSION=next npm run panda:sdk:install
    - npm run compile --prefix ../external/interop
    - npm run compile --prefix ../external/incremental/common
    - npm run compile --prefix ../external/incremental/compat
    - npm run compile --prefix ../external/incremental/runtime
    - npm run build:interop:inc --prefix ../external/interop
    - npm run build:incremental:inc --prefix ../external/incremental/runtime
  script:
    - cd $CI_PROJECT_DIR/ohosgen/demos/mediaquery
    - npm show @koalaui/interop && npm show @koalaui/common
    - npm i -d
    - npm run check:ts
    - npm run check:arkts
#   - npm run run:ohos:context:ts
#   - npm run check:ohos:context:run
    - cd $CI_PROJECT_DIR/ohosgen/tests/unit
    - npm run check:ts
    - npm run check:arkts
    - |
      cd $CI_PROJECT_DIR/ohosgen
      touch $CI_PROJECT_DIR/ohosgen/summary.txt
      test_status=0
      cat demos/expected.txt |
      while read pkg expected; do
        cd $pkg
        npm i -d
        npm run check:arkts && result=PASS || result=FAIL
        echo "$pkg: $result (expected $expected)" >> $CI_PROJECT_DIR/ohosgen/summary.txt
        if [ "$result" != "$expected" ]; then
          test_status=1
        fi
        cd $CI_PROJECT_DIR/ohosgen
      done
      echo "---------------RESULT-----------------"
      cat $CI_PROJECT_DIR/ohosgen/summary.txt
      echo "--------------------------------------"
      exit $test_status
