image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.2.5"

stages:
  - build
  - test
  - pre-deploy
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

include:
    - gitlab/setup.yml
    - gitlab/npm.yml

check generated XML demo:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    needs:
    - download sdk
    - build external
    before_script:
      - !reference [.npm, script]
      - !reference [.panda, script]
    script:
      - cd $CI_PROJECT_DIR/ohosgen/demos/xml
      - npm run check:ts
      - npm run check:arkts

check ohos unit tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build external
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/unit
    - npm run check:ts
    - npm run check:arkts
    - cd $CI_PROJECT_DIR/ohosgen/tests/dummy
    - npm run check:ts
    - npm run check:arkts
  # after_script:
  #   - !reference [.notify-telegram, script]

check ohos demos:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
  - download sdk
  - build external
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/demos/mediaquery
    - npm show @koalaui/interop && npm show @koalaui/common
    - npm i -d
    - npm run check:ts
    - npm run check:arkts
    - cd $CI_PROJECT_DIR/ohosgen/demos/context
#   - npm run check:ts
    - npm run check:arkts
    - cd $CI_PROJECT_DIR/ohosgen/demos/huks
    - npm run check:ts
    - npm run check:arkts

check ohos system tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build external
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/system
    - npm i -d
    - python3 run-system-tests.py
