image: "nexus.bz-openlab.ru:10443/huawei/koala-ci:0.2.2"

stages:
  - build
  - test
  - pre-deploy
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PANDA_SDK_VER: "1.5.0-dev.30153"

include:
    - gitlab/setup.yml
    - gitlab/npm.yml

check generated XML demo:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    before_script:
      - !reference [.setup, script]
      - cd $CI_PROJECT_DIR/ohosgen
      - export PANDA_SDK_VERSION=$PANDA_SDK_VER
      - npm run panda:sdk:check-install
      - npm run compile --prefix ../external/interop
      - npm run compile --prefix ../external/incremental/common
      - npm run compile --prefix ../external/incremental/compat
      - npm run compile --prefix ../external/incremental/runtime
      - npm run build:interop:inc --prefix ../external/interop
      - npm run build:incremental:inc --prefix ../external/incremental/runtime
    script:
      - cd demos/xml
      - npm run check:ts
      - npm run check:arkts

check ohos unit tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - cd $CI_PROJECT_DIR/ohosgen
    - export PANDA_SDK_VERSION=$PANDA_SDK_VER
    - npm run panda:sdk:check-install
    - npm run compile --prefix ../external/interop
    - npm run compile --prefix ../external/incremental/common
    - npm run compile --prefix ../external/incremental/compat
    - npm run compile --prefix ../external/incremental/runtime
    - npm run build:interop:inc --prefix ../external/interop
    - npm run build:incremental:inc --prefix ../external/incremental/runtime
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/unit
    - npm run check:ts
    - npm run check:arkts
    - cd $CI_PROJECT_DIR/ohosgen/tests/dummy
    - npm run check:ts
    - npm run check:arkts
  after_script:
    - !reference [.notify-telegram, script]

check ohos demos:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - cd $CI_PROJECT_DIR/ohosgen
    - export PANDA_SDK_VERSION=$PANDA_SDK_VER
    - npm run panda:sdk:check-install
    - npm run compile --prefix ../external/interop
    - npm run compile --prefix ../external/incremental/common
    - npm run compile --prefix ../external/incremental/compat
    - npm run compile --prefix ../external/incremental/runtime
    - npm run build:interop:inc --prefix ../external/interop
    - npm run build:incremental:inc --prefix ../external/incremental/runtime
  script:
    - cd $CI_PROJECT_DIR/ohosgen/demos/mediaquery
    - npm show @koalaui/interop && npm show @koalaui/common
    - npm i -d
    - npm run check:ts
    - npm run check:arkts
    - cd $CI_PROJECT_DIR/ohosgen/demos/context
#   - npm run check:ts
    - npm run check:arkts

check ohos system tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
    - cd $CI_PROJECT_DIR/ohosgen
    - export PANDA_SDK_VERSION=$PANDA_SDK_VER
    - npm run panda:sdk:check-install
    - npm run compile --prefix ../external/interop
    - npm run compile --prefix ../external/incremental/common
    - npm run compile --prefix ../external/incremental/compat
    - npm run compile --prefix ../external/incremental/runtime
    - npm run build:interop:inc --prefix ../external/interop
    - npm run build:incremental:inc --prefix ../external/incremental/runtime
  script:
    - cd $CI_PROJECT_DIR/ohosgen/system-tests
    - npm i -d
    - python3 run-system-tests.py
