[dependencies]
  Interop = { path = "../../../external/interop/src/cangjie" }
[package]
  cjc-version = "0.56.4"
  compile-option = "-L ./build/native/cangjie -l MEIDAQUERY_NativeBridgeCJ"
  description = "config file for cj-mediaquery build"
  link-option = ""
  name = "idlize"
  output-type = "executable"
  src-dir = "./generated/cangjie"
  target-dir = "./build/cangjie"
  version = "1.0.0"
  package-configuration = {}