[dependencies]
  KoalaRuntime = { path = "../external/incremental-cj/runtime"}
  Interop = { path = "../external/interop/src/cangjie" }
[package]
  cjc-version = "0.58.3"
  compile-option = "-L ./native/build-cangjie-native-dummy -l NativeBridgeCJ"
  description = "config file for cj build"
  link-option = ""
  name = "idlize"
  output-type = "executable"
  src-dir = "./out/cangjie-subset/generated/sig/arkoala-arkts/framework/cangjie/src"
  target-dir = "./build/cj"
  version = "1.0.0"
  package-configuration = {}
