[dependencies]
  KoalaRuntime = { path = "../external/incremental-cj/runtime"}
  Interop = { path = "../external/interop/src/cangjie" }
  idlize = { path = "out/cangjie/generated/sig/arkoala-cj/cjv2" }
[package]
  cjc-version = "0.59.6"
  compile-option = "--error-count-limit all --warn-off all -L ./native/build-cangjie-native-dummy -l NativeBridgeCJ -L ./../external/incremental-cj/runtime/callsitekey -l CallsiteKey"
  description = "config file for cj build"
  link-option = ""
  name = "demo"
  output-type = "executable"
  src-dir = "./out/cangjie/generated/sig/arkoala-cj/framework/cangjie/src"
  target-dir = "./build/cj"
  version = "1.0.0"
  package-configuration = {}
