build idlize-libarktsgen:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - npm run compile --prefix libarkts-gen

test libarktsgen:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.setup, script]
  script:
    - npm run all --prefix libarkts-gen
  needs:
    - install panda sdk

pack idlize-libarktsgen:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: libarkts-gen
  needs:
    - build idlize-libarktsgen

pre-publish test libarktsgen:
  stage: pre-publish
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [ .setup, script ]
  script:
    - cd $CI_PROJECT_DIR/libarkts-gen
    - npm pack
    - cd ../
    - npx --yes ./libarkts-gen/idlizer-libarkts-gen-*.tgz --panda-sdk-path ./external/incremental/tools/panda/node_modules/@panda/sdk --output-dir .
    - cd libarkts
    - npm i
    - npm run compile
  needs:
    - build idlize-libarktsgen
    - install panda sdk

publish idlize-libarktsgen:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: libarkts-gen
  dependencies:
    - build idlize-arkgen

install panda sdk:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [ .setup, script ]
    - cd $CI_PROJECT_DIR
  script:
    - PANDA_SDK_VERSION=next npm run --prefix ./external/incremental/tools/panda panda:sdk:install
  artifacts:
    expire_in: 2 days
    paths:
      - external/incremental/tools/panda/node_modules
