build idlize-arktscgen:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  script:
    - !reference [.npm, script]
    - npm run compile --prefix arktscgen

test arktscgen:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - npm run all --prefix arktscgen

pack idlize-arktscgen:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: arktscgen
  dependencies:
    - build idlize-arktscgen

pre-publish test arktscgen:
  allow_failure: true
  stage: pre-publish
  dependencies:
  - build idlize-arktscgen
  tags:
    - idlize-ci
    - koala-ci
  script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - npm run test:pack --prefix arktscgen

publish idlize-arktscgen:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: arktscgen
  dependencies:
    - build idlize-arkgen

