build idlize-arktscgen:
  stage: build
  needs:
  - npm install
  tags:
    - idlize-ci
    - koala-ci
  script:
    - npm run compile --prefix arktscgen

test arktscgen:
  allow_failure: true
  stage: test
  needs:
  - npm install
  - panda sdk install
  tags:
    - idlize-ci
    - koala-ci
  script:
    - npm run all --prefix arktscgen

pack idlize-arktscgen:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: arktscgen
  needs:
    - build idlize-arktscgen

pre-publish test arktscgen:
  allow_failure: true
  stage: pre-publish
  needs:
  - npm install
  - build idlize-arktscgen
  - panda sdk install
  tags:
    - idlize-ci
    - koala-ci
  script:
    - npm run test:pack --prefix arktscgen

publish idlize-arktscgen:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: arktscgen
  dependencies:
    - build idlize-arkgen

