# Copyright (c) 2022-2023 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

build compiler-plugin:
    stage: build-compiler
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - npm ci --no-audit --no-fund
        - cd compiler-plugin
    script:
        - npm run compile
    needs:
        - build compat
        - build common
    artifacts:
        expire_in: 2 days
        paths:
            - compiler-plugin/build/lib

test compiler-plugin:
    stage: test
    interruptible: true
    extends: .linux-vm-shell-task
    before_script:
        - !reference [.setup, script]
        - cd compiler-plugin
    script:
        - npm run test
    needs:
        - build compat
        - build common
        - build compiler-plugin

pack compiler-plugin:
    extends: 
        - .npm-pack
        - .linux-vm-shell-task
    variables:
        PACKAGE_DIR: compiler-plugin
    needs:
        - build compiler-plugin
        - test compiler-plugin

publish compiler-plugin:
    extends: 
        - .npm-publish
        - .linux-vm-shell-task
    variables:
        PACKAGE_DIR: compiler-plugin
    dependencies:
        - build compiler-plugin
        - test compiler-plugin

publish compiler-plugin (release):
    extends: 
        - .npm-publish-release
        - .linux-vm-shell-task
    variables:
        PACKAGE_DIR: compiler-plugin
    dependencies:
        - build compiler-plugin
        - test compiler-plugin
